### ISSUE TITLE
Cannot get Proactive Express working for Qlik Sense Sep 2018

### ISSUE THREAD

**Issue by chanirban** [BjarniPeturFridjonsson/Qlik-SupportTools#3]
Service for Proactive Express is running successfully but still getting the error 
![image](https://user-images.githubusercontent.com/12374664/55620985-eb508600-57b9-11e9-9f8d-e3ffc28ca99a.png)

Followed the instruction for Proxy but no joy. Log attached too.
[log.zip](https://github.com/BjarniPeturFridjonsson/Qlik-SupportTools/files/3047418/log.zip)

**Comment by BjarniPeturFridjonsson** [comment]
It is a service that is installed? Why are you trying to run it as an windows exe file? 
You can control the service from the Services MMC.  

Now the logs shows that it is not able to send the information back to Qlik. Has the server open https port?

**Comment by BjarniPeturFridjonsson** [comment]
This issue was just due to trying to run a service as an exe file.
